### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by smoki3** [AndyEveritt/ASMBL#37]
It seems that it is only running on Windows right?

**Comment by AndyEveritt** [comment]
Unfortunately I do not have a mac to test on. There is no reason I can think that it shouldn't work on mac, you may just need to enable it in `ASMBL.manifest` potentially.

The standalone version would be the first thing to check if it works. The code doesn't use any non standard python libraries (for Fusion API reasons).

Would be happy to help you get it working on mac. Let me know how you get on

**Comment by smoki3** [comment]
Hi Andy, 

I am able to load the plugin in fusion. but the output is not working.

This is what I get:
<img width="417" alt="Bildschirmfoto 2020-09-03 um 23 20 04" src="https://user-images.githubusercontent.com/9723729/92173056-343bbc80-ee3c-11ea-9376-e797bd85a2a7.png">

**Comment by smoki3** [comment]
<img width="408" alt="Bildschirmfoto 2020-09-03 um 23 35 09" src="https://user-images.githubusercontent.com/9723729/92176130-238c4600-ee3e-11ea-8e20-7056c4a35120.png">

and also sometimes this

**Comment by smoki3** [comment]
If I try to run the main.py I also run into this:

`kevin@Kevins-MBP-2018 ASMBL % python3 main.py
parsing files...
Opening files...
Converting additive gcode to relative positioning...
Spliting additive gcode layers...
Spliting subtractive gcode layers...
Ordering subtractive gcode layers...
Merging gcode layers...
Creating gcode script...
saving output...
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    asmbl_parser.create_output_file(asmbl_parser.merged_gcode_script)
  File "/Users/kevin/Documents/3D Drucker/ASMBL/src/ASMBL_parser.py", line 343, in create_output_file
    os.startfile(file_path)
AttributeError: module 'os' has no attribute 'startfile'`

The result is an gcode file but it is not aligned

**Comment by AndyEveritt** [comment]
Interesting. Would you mind exporting the f3d file from fusion. I haven't seen that issue before but if I can find the cause I can fix that next week. My guess is its an issue with the CAM setup

**Comment by AndyEveritt** [comment]
Please can you also tick the `view intermediate files` in Fusion and send the `tmpAdditive.gcode` and `tmpSubtractive.gcode` in the folder it opens

**Comment by AndyEveritt** [comment]
The alignment is done in `config.json` fyi

**Comment by AndyEveritt** [comment]
Also very odd that the standalone works. They are fundamentally using the same code. Fusion just adds a GUI

**Comment by AndyEveritt** [comment]
Also the os.startfile appears to not be a thing on mac. Will see if there is an alternative next week

**Comment by smoki3** [comment]
[Gcodes.zip](https://github.com/AndyEveritt/ASMBL/files/5171553/Gcodes.zip)

these are the gcodes.

**Comment by smoki3** [comment]
got it aligned with editing the config.json. So manual executing the main.py gives me now a working gcodes. Just still get this os.startfile issue. 

This is my test project
[ASMBL Test v8.f3d.zip](https://github.com/AndyEveritt/ASMBL/files/5171570/ASMBL.Test.v8.f3d.zip)

**Comment by smoki3** [comment]
got this fixed by a simple condition:

`        try:
                if sys.platform == "win32":
                    os.startfile(file_path)
                else:
                    opener ="open" if sys.platform == "darwin" else "xdg-open"
                    subprocess.call([opener, file_path])`

**Comment by AndyEveritt** [comment]
Thanks for doing the openwith fix. Will implement that when I'm back in office. It bizzare that the standalone works but fusion doesn't. Are you using the same 2 input gcode files?

**Comment by smoki3** [comment]
Yes I use the same files.

I assume that the plugin is looking for some parameters in fusion? And may they are different between win and osx. 

I did some further testing and I was able to get some results without error message. But the merged gcode is broken. The additive part is just half finished

**Comment by AndyEveritt** [comment]
That's very strange. I wonder if the post processors work differently on mac 🤔

**Comment by AndyEveritt** [comment]
The other thought is to preview the 2 tmp gcode files in simplify. That will tell us if it is an issue with merging or the input files

**Comment by AndyEveritt** [comment]
Just you try importing the spinner f3d from the examples folder and let me know if that setup works

**Comment by smoki3** [comment]
So the 2 gcodes files (cam and additive) are looking good in simplifiy. Just the merged output is broken. Nevertheless as soon I do some more complex milling process it did fail with the issus from the screen shot

**Comment by smoki3** [comment]
<img width="305" alt="Bildschirmfoto 2020-09-04 um 08 53 09" src="https://user-images.githubusercontent.com/9723729/92208719-14cc8000-ee8c-11ea-819a-21b0049e6a2b.png">


I get this when opening the spinner demo.

**Comment by AndyEveritt** [comment]
That should be fine. The errors are just saying the operations are suppressed (leave them that way, I was trying some funky stuff) the warning is because the Retract height is too low for traditional milling... But we aren't doing traditional milling 😜

**Comment by smoki3** [comment]
Okay then I get this again:

<img width="447" alt="Bildschirmfoto 2020-09-04 um 08 57 16" src="https://user-images.githubusercontent.com/9723729/92209072-af2cc380-ee8c-11ea-80ad-f60a5bf20060.png">

but if I merge the two gcodes manually with the main.py it looks like this :):
<img width="562" alt="Bildschirmfoto 2020-09-04 um 08 58 30" src="https://user-images.githubusercontent.com/9723729/92209206-e8653380-ee8c-11ea-9bda-1fccc8357e7d.png">

**Comment by smoki3** [comment]
If I check the "Gernerate Toolpath" Option I get this:

<img width="427" alt="Bildschirmfoto 2020-09-04 um 09 00 34" src="https://user-images.githubusercontent.com/9723729/92209327-1c405900-ee8d-11ea-806b-3feb8594661e.png">

**Comment by AndyEveritt** [comment]
That's so frickin bizzare. I will try to look into it more next week. For now I would recommend using the standalone version since it seems to work.

**Comment by AndyEveritt** [comment]
Also the generate toolpath button is buggy as hell due to bugs with the Fusion API, until they fix that it won't really work that well so probably best to avoid

**Comment by smoki3** [comment]
Okay fine 👍 

If you need something more just tell me :)

**Comment by AndyEveritt** [comment]
Sorry for the issues though . Hopefully we can resolve them fairly quickly 😊

**Comment by smoki3** [comment]
No Problem :) I am here to fix it 👍

**Comment by smoki3** [comment]
Have you made some progress on this?

**Comment by AndyEveritt** [comment]
I was unable to recreate the issue my end. I did notice an error in your setup but don't think that it would cause the issue you were having,

In the `Linking` tab, you had a `Helix` ramp type
![image](https://user-images.githubusercontent.com/38423143/94542866-36c5e200-0241-11eb-91b4-574eb04d22cf.png)

This should have been set to `Plunge` `No contact`
![image](https://user-images.githubusercontent.com/38423143/94542918-4b09df00-0241-11eb-84dc-0ab0399a9c8d.png)

Its on my to do to warn users if they have not changed this themselves.

**Comment by AndyEveritt** [comment]
My best guess is this logic in `src\fusion_api\Handlers.py` doesn't work on Mac and the individual gcode files are not created fully before the parser tries to combine them, do you think you would be able to have a play to see if you can figure out a solution as I still don't have a mac available to test.

```python
        try:
            start = time.time()
            postToolpaths(ui, cam, viewIntermediateFiles)
            while not (os.path.exists(tmpAdditive) and os.path.exists(tmpSubtractive)):
                if time.time() > start + 10:
                    ui.messageBox('Posting timed out')
                    return
                pass    # wait until files exist
            checkpoint = time.time()
            while True:
                if time.time() > checkpoint + 10:
                    ui.messageBox('Permission Error timed out')
                    return
                try:
                    open(tmpAdditive)
                    open(tmpSubtractive)
                    break
                except PermissionError:
                    continue
        except:
            ui.messageBox('Failed posting toolpaths:\n{}'.format(traceback.format_exc()))
            return
```

**Comment by smoki3** [comment]
I will have a try this week.

Meanwhile could you merge this to fix the first issue on mac:

```
 try:
                if sys.platform == "win32":
                    os.startfile(file_path)
                else:
                    opener ="open" if sys.platform == "darwin" else "xdg-open"
                    subprocess.call([opener, file_path])
```

**Comment by AndyEveritt** [comment]
That change should be in master already. Will create a new release later today

**Comment by AndyEveritt** [comment]
https://github.com/AndyEveritt/ASMBL/releases/tag/v2.3.2

**Comment by smoki3** [comment]
So I tested the new release in manual mode but this doesn't work on mac

```
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    asmbl_parser.create_output_file(asmbl_parser.merged_gcode_script)
  File "/Users/kevin/Documents/3D Drucker/ASMBL/src/ASMBL_parser.py", line 333, in create_output_file
    os.startfile(file_path)
AttributeError: module 'os' has no attribute 'startfile'
```

**Comment by smoki3** [comment]
Ah you forgot to add this to ASMBL_parser.py

**Comment by smoki3** [comment]
So you was right. It a timing issue between the gcode generation and the merging process.

I added a `time.sleep(20)` before the merging process then it is working fine.

**Comment by smoki3** [comment]
https://github.com/AndyEveritt/ASMBL/pull/41

**Comment by AndyEveritt** [comment]
Cheers, if you are happy that it is working on mac now then I will merge with master and make a new release again?

**Comment by smoki3** [comment]
Tested it now with a different models! Working fine so far. So I think you can merge it

**Comment by AndyEveritt** [comment]
Just done a refactor, could you check it still works then I will merge to master
